sudo: false
language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn --ignore-engines

script:
  - make test-ci-coverage
